import type { CanvasGraphSnapshot } from '../../state/canvas-graph-store'

export const complexCanvasTemplate: CanvasGraphSnapshot = {
  nodes: [
    { id: 'start-1', type: 'start', x: 180, y: 340, startWeightingType: 'specificPercentage', startSpecificPercentages: { 'token-btc': '50', 'token-eth': '30', 'stock-nvda': '20' } },
    { id: 'token-btc', type: 'token', x: 470, y: 160, assetSymbol: 'BTC', assetName: 'Bitcoin' },
    { id: 'token-eth', type: 'token', x: 470, y: 340, assetSymbol: 'ETH', assetName: 'Ethereum' },
    { id: 'stock-nvda', type: 'stock', x: 470, y: 520, assetSymbol: 'NVDA', assetName: 'NVIDIA' },
    { id: 'filter-1', type: 'filter', x: 820, y: 340, filterAssetNodeId: 'token-btc', filterSortFunction: 'rsi', filterSortPeriod: '14', filterConditionOperator: 'and', filterSecondarySortFunction: 'volume', filterOrdering: 'top', filterHowMany: '2', filterResultMode: 'topN', filterConfigsByAssetNodeId: { 'token-btc': { filterSortFunction: 'rsi', filterSortPeriod: '14', filterConditionOperator: 'and', filterSecondarySortFunction: 'volume', filterOrdering: 'top', filterHowMany: '2', filterResultMode: 'topN' }, 'token-eth': { filterSortFunction: 'exponentialMovingAverage', filterSortPeriod: '20', filterConditionOperator: 'or', filterSecondarySortFunction: 'atr', filterSecondarySortPeriod: '14', filterOrdering: 'top', filterHowMany: '1', filterResultMode: 'topOne' }, 'stock-nvda': { filterSortFunction: 'currentPrice', filterConditionOperator: 'and', filterSecondarySortFunction: 'macdHistogram', filterOrdering: 'bottom', filterHowMany: '1', filterResultMode: 'allMatches' } } },
    { id: 'if-btc-1', type: 'if', x: 1180, y: 180, ifSourceType: 'market', ifConditionType: 'threshold', ifPrimaryFunction: 'rsi', ifPrimaryAssetNodeId: 'token-btc', ifPrimaryPeriod: '14', ifComparator: '<', ifComparisonValue: '30' },
    { id: 'if-nvda-1', type: 'if', x: 1180, y: 500, ifConditionType: 'threshold', ifPrimaryFunction: 'simpleMovingAverage', ifPrimaryAssetNodeId: 'stock-nvda', ifPrimaryPeriod: '20', ifComparator: '>', ifComparisonValue: '1100' },
    { id: 'and-1', type: 'and', x: 1520, y: 260 },
    { id: 'or-1', type: 'or', x: 1520, y: 580 },
    { id: 'not-1', type: 'not', x: 1520, y: 120 },
    { id: 'xor-1', type: 'xor', x: 1520, y: 740 },
    { id: 'filter-growth-1', type: 'filter', x: 1180, y: 920, filterAssetNodeId: 'token-eth', filterSortFunction: 'volume', filterConditionOperator: 'and', filterSecondarySortFunction: 'percentGain', filterOrdering: 'top', filterHowMany: '2' },
    { id: 'filter-value-1', type: 'filter', x: 1180, y: 1100, filterAssetNodeId: 'stock-nvda', filterSortFunction: 'currentMarketCap', filterConditionOperator: 'or', filterSecondarySortFunction: 'atr', filterSecondarySortPeriod: '14', filterOrdering: 'bottom', filterHowMany: '1' },
    { id: 'intersect-1', type: 'intersect', x: 1520, y: 1010 },
    { id: 'union-1', type: 'union', x: 1520, y: 1180 },
    { id: 'exclude-1', type: 'exclude', x: 1880, y: 1100 },
    { id: 'if-logic-1', type: 'if', x: 2240, y: 1100, ifConditionType: 'threshold', ifPrimaryFunction: 'rsi', ifPrimaryAssetNodeId: 'token-eth', ifPrimaryPeriod: '14', ifComparator: '<', ifComparisonValue: '40' },
    { id: 'portfolio-condition-1', type: 'portfolioCondition', x: 1880, y: 20, portfolioMetric: 'cashPercent', portfolioComparator: '>=', portfolioValue: '15' },
    { id: 'position-limit-1', type: 'positionLimit', x: 1880, y: 100, positionLimitMode: 'percentage', positionLimitValue: '20', positionLimitApplyTo: 'singleAsset' },
    { id: 'buy-1', type: 'buy', x: 1880, y: 200, actionAssetNodeId: 'token-btc', actionAmountMode: 'percentage', actionAmountValue: '25', buyType: 'open' },
    { id: 'allocate-1', type: 'allocate', x: 2240, y: 200, allocateWeightingMode: 'percentage', allocateAmountValue: '15', allocateStyle: 'targetWeight' },
    { id: 'take-profit-1', type: 'takeProfit', x: 2600, y: 120, riskAssetNodeId: 'stock-nvda', riskComparator: '>=', riskThresholdValue: '1200', takeProfitMode: 'partial' },
    { id: 'stop-loss-1', type: 'stopLoss', x: 2600, y: 280, riskAssetNodeId: 'token-btc', riskComparator: '<=', riskThresholdValue: '58000', stopLossMode: 'trailing' },
    { id: 'cooldown-1', type: 'cooldown', x: 2960, y: 200, cooldownDuration: '7', cooldownUnit: 'day', cooldownScope: 'branch' },
    { id: 'loop-1', type: 'loop', x: 3320, y: 200, loopType: 'timeInterval', loopIntervalValue: '7', loopTimeUnit: 'day', loopRunMode: 'oncePerPeriod', loopPostAction: 'cooldown', loopPostActionValue: '2', loopPostActionUnit: 'day' },
    { id: 'else-1', type: 'else', x: 1880, y: 580 },
    { id: 'sell-1', type: 'sell', x: 2240, y: 500, actionAssetNodeId: 'token-eth', actionAmountMode: 'percentage', actionAmountValue: '20', sellType: 'reduce' },
    { id: 'scale-out-1', type: 'scaleOut', x: 2240, y: 680, scaleOutPercent: '10' },
    { id: 'exposure-limit-1', type: 'exposureLimit', x: 2240, y: 920, exposureLimitType: 'portfolio', riskComparator: '>=', exposureLimitValue: '65' },
    { id: 'rebalance-logic-1', type: 'rebalance', x: 2240, y: 1010, rebalanceMode: 'equal', rebalanceThreshold: '3', rebalanceScope: 'selectedAssets' },
    { id: 'rebalance-1', type: 'rebalance', x: 2600, y: 580, rebalanceMode: 'target', rebalanceThreshold: '5', rebalanceScope: 'branch' },
    { id: 'loop-logic-1', type: 'loop', x: 2600, y: 1010, loopType: 'driftThreshold', loopDriftThreshold: '4' },
    { id: 'end-logic-1', type: 'end', x: 2960, y: 1010, endType: 'positionConcentration', endOperator: '>=', endTargetValue: '35' },
    { id: 'end-1', type: 'end', x: 2960, y: 580, endType: 'maxDrawdown', endOperator: '<=', endTargetValue: '12' },
  ],
  selectedNodeIds: [],
  edges: [
    { id: 'edge-1', fromNodeId: 'start-1', fromSide: 'right', toNodeId: 'token-btc', toSide: 'left' },
    { id: 'edge-2', fromNodeId: 'start-1', fromSide: 'right', toNodeId: 'token-eth', toSide: 'left' },
    { id: 'edge-3', fromNodeId: 'start-1', fromSide: 'right', toNodeId: 'stock-nvda', toSide: 'left' },
    { id: 'edge-4', fromNodeId: 'token-btc', fromSide: 'right', toNodeId: 'filter-1', toSide: 'left' },
    { id: 'edge-5', fromNodeId: 'token-eth', fromSide: 'right', toNodeId: 'filter-1', toSide: 'left' },
    { id: 'edge-6', fromNodeId: 'stock-nvda', fromSide: 'right', toNodeId: 'filter-1', toSide: 'left' },
    { id: 'edge-7', fromNodeId: 'filter-1', fromSide: 'top', toNodeId: 'if-btc-1', toSide: 'left' },
    { id: 'edge-8', fromNodeId: 'filter-1', fromSide: 'bottom', toNodeId: 'if-nvda-1', toSide: 'left' },
    { id: 'edge-9', fromNodeId: 'if-btc-1', fromSide: 'right', toNodeId: 'and-1', toSide: 'left' },
    { id: 'edge-10', fromNodeId: 'if-nvda-1', fromSide: 'right', toNodeId: 'and-1', toSide: 'left' },
    { id: 'edge-11', fromNodeId: 'if-btc-1', fromSide: 'top', toNodeId: 'not-1', toSide: 'left' },
    { id: 'edge-12', fromNodeId: 'if-nvda-1', fromSide: 'bottom', toNodeId: 'or-1', toSide: 'left' },
    { id: 'edge-12b', fromNodeId: 'not-1', fromSide: 'right', toNodeId: 'or-1', toSide: 'top' },
    { id: 'edge-13a', fromNodeId: 'and-1', fromSide: 'top', toNodeId: 'portfolio-condition-1', toSide: 'left' },
    { id: 'edge-13b', fromNodeId: 'portfolio-condition-1', fromSide: 'right', toNodeId: 'position-limit-1', toSide: 'left' },
    { id: 'edge-13', fromNodeId: 'position-limit-1', fromSide: 'right', toNodeId: 'buy-1', toSide: 'left' },
    { id: 'edge-14', fromNodeId: 'buy-1', fromSide: 'right', toNodeId: 'allocate-1', toSide: 'left' },
    { id: 'edge-15', fromNodeId: 'allocate-1', fromSide: 'right', toNodeId: 'take-profit-1', toSide: 'left' },
    { id: 'edge-16', fromNodeId: 'allocate-1', fromSide: 'bottom', toNodeId: 'stop-loss-1', toSide: 'left' },
    { id: 'edge-17', fromNodeId: 'take-profit-1', fromSide: 'right', toNodeId: 'cooldown-1', toSide: 'left' },
    { id: 'edge-18', fromNodeId: 'stop-loss-1', fromSide: 'right', toNodeId: 'cooldown-1', toSide: 'left' },
    { id: 'edge-18a', fromNodeId: 'cooldown-1', fromSide: 'right', toNodeId: 'loop-1', toSide: 'left' },
    { id: 'edge-19', fromNodeId: 'or-1', fromSide: 'right', toNodeId: 'else-1', toSide: 'left' },
    { id: 'edge-20', fromNodeId: 'else-1', fromSide: 'top', toNodeId: 'sell-1', toSide: 'left' },
    { id: 'edge-21', fromNodeId: 'else-1', fromSide: 'bottom', toNodeId: 'scale-out-1', toSide: 'left' },
    { id: 'edge-21b', fromNodeId: 'if-btc-1', fromSide: 'bottom', toNodeId: 'xor-1', toSide: 'left' },
    { id: 'edge-21c', fromNodeId: 'if-nvda-1', fromSide: 'top', toNodeId: 'xor-1', toSide: 'top' },
    { id: 'edge-22', fromNodeId: 'sell-1', fromSide: 'right', toNodeId: 'rebalance-1', toSide: 'left' },
    { id: 'edge-23', fromNodeId: 'scale-out-1', fromSide: 'right', toNodeId: 'rebalance-1', toSide: 'left' },
    { id: 'edge-24', fromNodeId: 'rebalance-1', fromSide: 'right', toNodeId: 'end-1', toSide: 'left' },
    { id: 'edge-25', fromNodeId: 'token-btc', fromSide: 'bottom', toNodeId: 'filter-growth-1', toSide: 'left' },
    { id: 'edge-26', fromNodeId: 'token-eth', fromSide: 'bottom', toNodeId: 'filter-growth-1', toSide: 'left' },
    { id: 'edge-27', fromNodeId: 'token-eth', fromSide: 'bottom', toNodeId: 'filter-value-1', toSide: 'left' },
    { id: 'edge-28', fromNodeId: 'stock-nvda', fromSide: 'bottom', toNodeId: 'filter-value-1', toSide: 'left' },
    { id: 'edge-29', fromNodeId: 'filter-growth-1', fromSide: 'right', toNodeId: 'intersect-1', toSide: 'left' },
    { id: 'edge-30', fromNodeId: 'filter-value-1', fromSide: 'right', toNodeId: 'intersect-1', toSide: 'left' },
    { id: 'edge-31', fromNodeId: 'filter-growth-1', fromSide: 'bottom', toNodeId: 'union-1', toSide: 'left' },
    { id: 'edge-32', fromNodeId: 'filter-value-1', fromSide: 'bottom', toNodeId: 'union-1', toSide: 'left' },
    { id: 'edge-33', fromNodeId: 'union-1', fromSide: 'right', toNodeId: 'exclude-1', toSide: 'left' },
    { id: 'edge-34', fromNodeId: 'intersect-1', fromSide: 'right', toNodeId: 'exclude-1', toSide: 'top' },
    { id: 'edge-35', fromNodeId: 'xor-1', fromSide: 'right', toNodeId: 'rebalance-logic-1', toSide: 'left' },
    { id: 'edge-36', fromNodeId: 'exclude-1', fromSide: 'right', toNodeId: 'if-logic-1', toSide: 'left' },
    { id: 'edge-36a', fromNodeId: 'exclude-1', fromSide: 'bottom', toNodeId: 'exposure-limit-1', toSide: 'left' },
    { id: 'edge-36b', fromNodeId: 'exposure-limit-1', fromSide: 'right', toNodeId: 'rebalance-logic-1', toSide: 'top' },
    { id: 'edge-37', fromNodeId: 'if-logic-1', fromSide: 'right', toNodeId: 'rebalance-logic-1', toSide: 'bottom' },
    { id: 'edge-38', fromNodeId: 'rebalance-logic-1', fromSide: 'right', toNodeId: 'loop-logic-1', toSide: 'left' },
    { id: 'edge-39', fromNodeId: 'loop-logic-1', fromSide: 'right', toNodeId: 'end-logic-1', toSide: 'left' },
  ],
  selectedEdgeIds: [],
}
