import { CaretDown } from '@phosphor-icons/react'
import { useMemo, useRef, useState } from 'react'

import type { CanvasLimitMode, CanvasNodeRecord, CanvasPositionLimitApplyTo } from '../../state/canvas-node-store'
import CanvasNodeSidebarHeader from './canvas-node-sidebar-header'
import CanvasSidebarFieldSection from './canvas-sidebar-field-section'
import DropdownMenu, { type DropdownMenuItem } from '../dropdown/dropdown-menu'

const modeOptions: Array<{ value: CanvasLimitMode; label: string }> = [{ value: 'percentage', label: 'Percentage' }, { value: 'value', label: 'Value' }]
const applyOptions: Array<{ value: CanvasPositionLimitApplyTo; label: string }> = [{ value: 'singleAsset', label: 'Single Asset' }, { value: 'branchAssets', label: 'Branch Assets' }]

export default function CanvasPositionLimitSidebar({ active, node, onClose, onModeChange, onApplyToChange, onValueChange }: { active: boolean; node: CanvasNodeRecord | null; onClose: () => void; onModeChange: (value: CanvasLimitMode) => void; onApplyToChange: (value: CanvasPositionLimitApplyTo) => void; onValueChange: (value: string) => void }) {
  const containerRef = useRef<HTMLDivElement | null>(null)
  const [isModeOpen, setIsModeOpen] = useState(false)
  const [isApplyOpen, setIsApplyOpen] = useState(false)
  const selectedMode = modeOptions.find((option) => option.value === node?.positionLimitMode) ?? modeOptions[0]
  const selectedApply = applyOptions.find((option) => option.value === node?.positionLimitApplyTo) ?? applyOptions[0]
  const modeGroups = useMemo(() => [{ items: modeOptions.map<DropdownMenuItem>((option) => ({ label: option.label, value: option.value, active: option.value === selectedMode.value, trailingIcon: option.value === selectedMode.value ? '✓' : undefined })) }], [selectedMode.value])
  const applyGroups = useMemo(() => [{ items: applyOptions.map<DropdownMenuItem>((option) => ({ label: option.label, value: option.value, active: option.value === selectedApply.value, trailingIcon: option.value === selectedApply.value ? '✓' : undefined })) }], [selectedApply.value])

  return <aside aria-hidden={!active} style={{ position: 'absolute', top: 72, left: 18, width: 280, minHeight: 188, maxHeight: 'calc(100vh - 164px)', borderRadius: 20, border: '1px solid var(--canvas-panel-divider)', background: 'color-mix(in srgb, var(--canvas-surface) 92%, transparent)', boxShadow: '0 16px 40px var(--canvas-shadow-soft)', backdropFilter: 'blur(16px)', display: 'flex', flexDirection: 'column', overflow: 'hidden', pointerEvents: active ? 'auto' : 'none', opacity: active ? 1 : 0, transform: active ? 'translateX(0)' : 'translateX(-16px)', transition: 'opacity 180ms ease, transform 180ms ease', zIndex: 3 }}>
    <CanvasNodeSidebarHeader title="Position Limit" description="Represents a max size rule for positions in this flow." helpTitle="Position Limit" helpBody="Use this node when the builder should show a size cap before entries or allocations continue." closeLabel="Close position limit sidebar" onClose={onClose} />
    <div ref={containerRef} style={{ flex: 1, minHeight: 0, overflowY: 'auto', padding: 18, display: 'flex', flexDirection: 'column', gap: 10 }}>
      <CanvasSidebarFieldSection title="Limit mode" description="Choose whether the position cap is shown as a percentage or value."><button type="button" onClick={() => setIsModeOpen((current) => !current)} style={{ width: '100%', minHeight: 54, borderRadius: 16, border: '1px solid var(--canvas-panel-divider)', background: 'var(--canvas-surface-soft)', padding: '0 14px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', cursor: 'pointer' }}><span style={{ color: 'var(--canvas-text-primary)', fontFamily: 'var(--canvas-font-sans)', fontSize: 13, fontWeight: 700 }}>{selectedMode.label}</span><CaretDown size={14} weight="bold" /></button>{isModeOpen ? <DropdownMenu open={isModeOpen} boundaryRef={containerRef} groups={modeGroups} position="bottom" portalToBody onItemClick={(item) => { onModeChange(item.value as CanvasLimitMode); setIsModeOpen(false) }} /> : null}</CanvasSidebarFieldSection>
      <CanvasSidebarFieldSection title="Apply to" description="Choose whether this node applies per asset or to branch assets."><button type="button" onClick={() => setIsApplyOpen((current) => !current)} style={{ width: '100%', minHeight: 54, borderRadius: 16, border: '1px solid var(--canvas-panel-divider)', background: 'var(--canvas-surface-soft)', padding: '0 14px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', cursor: 'pointer' }}><span style={{ color: 'var(--canvas-text-primary)', fontFamily: 'var(--canvas-font-sans)', fontSize: 13, fontWeight: 700 }}>{selectedApply.label}</span><CaretDown size={14} weight="bold" /></button>{isApplyOpen ? <DropdownMenu open={isApplyOpen} boundaryRef={containerRef} groups={applyGroups} position="bottom" portalToBody onItemClick={(item) => { onApplyToChange(item.value as CanvasPositionLimitApplyTo); setIsApplyOpen(false) }} /> : null}</CanvasSidebarFieldSection>
      <CanvasSidebarFieldSection title="Limit value" description="Enter the limit this rule should show in the builder." showDivider={false}><div style={{ minHeight: 54, borderRadius: 16, border: '1px solid var(--canvas-panel-divider)', background: 'var(--canvas-surface-soft)', padding: '0 14px', display: 'flex', alignItems: 'center', gap: 8 }}><span style={{ color: 'var(--canvas-text-secondary)', fontFamily: 'var(--canvas-font-sans)', fontSize: 14, fontWeight: 700 }}>{selectedMode.value === 'percentage' ? '%' : '$'}</span><input value={node?.positionLimitValue ?? ''} onChange={(event) => onValueChange(event.target.value)} placeholder="10" inputMode="decimal" style={{ width: '100%', border: 'none', outline: 'none', background: 'transparent', color: 'var(--canvas-text-primary)', fontFamily: 'var(--canvas-font-sans)', fontSize: 14, fontWeight: 700, padding: 0 }} /></div></CanvasSidebarFieldSection>
    </div>
  </aside>
}
